# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Jayoung Ryu
url:              https://github.com/jykr/
#baseurl:          '/hydeout'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           Jayoung Ryu
  email: jayoung_ryu@g.harvard.edu
  url:            jykr.github.io
  

#paginate:         5
# paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# remote_theme: fongandrew/hydeout  (removed â€” using custom single-page design)
#encoding: utf-8
